// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvtsbnivuysunnjrpndk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2dHNibml2dXlzdW5uanJwbmRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTU2OTMsImV4cCI6MjA3MzM3MTY5M30.F2jdRSnEJYKD8ryCFRbGZUC6_ksED6iPVDhc638STd8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});